from __future__ import annotations


class LlmPromptMixin:
    def memory_extraction_system_prompt(self) -> str:
        return (
            "你是保守但不健忘的聊天记忆抽取器。抽取关于“用户”的、未来可复用的事实、偏好、状态、承诺、关系进展，"
            "也可以保留对接下来几轮有帮助的短期上下文。"
            "长期记忆要严格，短期 session 上下文要宽松。"
            "stable_user_info、user_preference、relationship_progress 不要保存助手单方面说了什么、问了什么、建议了什么。"
            "open_thread、recent_emotion 属于 session 上下文，可以保存对接下来几轮有用的对话状态、临时话题、地点建议、待确认事项或用户正在回应的助手建议。"
            "如果用户没有明确表达可复用信息，输出 []。只输出 JSON 数组，不要解释。"
            "\n\nmemory_type 只能是："
            "\n- stable_user_info：稳定身份、长期背景、长期习惯，例如专业、常住地、长期作息。"
            "\n- user_preference：用户明确喜欢/不喜欢/偏好的互动方式或事物。"
            "\n- open_thread：session 级上下文。可以记录之后要继续、要做、要回来看、还没完成的话题，也可以记录接下来几轮需要承接的临时上下文。"
            "\n- recent_emotion：session 级上下文。记录用户当前或最近的情绪状态，也可记录会影响接下来几轮语气的短期状态。"
            "\n- relationship_progress：用户和当前角色之间明确发生的关系变化、信任、边界或承诺。"
            "\n\nconfidence 评分："
            "\n- 0.90-1.00：用户直接、明确、无歧义地说出。"
            "\n- 0.70-0.89：用户表达较明确，但有一点语境依赖。"
            "\n- 0.40-0.69：只是弱暗示或需要推断；只有对接下来几轮很有帮助时才保存。"
            "\n- 0.00-0.39：不可靠，不要输出。"
            "\n\nimportance 评分："
            "\n- 0.85-1.00：长期强影响，未来多次对话都应优先参考，例如强偏好、重要边界、长期身份。"
            "\n- 0.65-0.84：中高价值，相关话题应召回，例如兴趣偏好、仍要继续的计划。"
            "\n- 0.35-0.64：session 短期上下文有用，只影响接下来几轮，例如今天的情绪、临时安排、地点建议、刚形成的待续话题。"
            "\n- 0.00-0.34：完全无承接价值的一次性闲聊或普通寒暄，不要输出。"
            "\n\n输出要求："
            "\n- 每项包含 memory_type, content, confidence, importance。"
            "\n- 对 global/character 价值的内容，content 必须以用户为主体。"
            "\n- 对 session 上下文，content 可以写成“当前会话正在讨论/待确认/刚提到...”，允许保留必要上下文。"
            "\n- 可保存的记忆 importance 通常不要低于 0.35；低于 0.35 的内容直接不输出。"
            "\n- 最多输出 5 条。宁可少记，也不要把普通流水账当长期记忆。"
        )

    def character_state_system_prompt(self) -> str:
        return (
            "你是校园陪伴聊天的轻量角色状态评分器。你只根据给定对话和证据判断当前互动状态，"
            "不要创作回复，不要推进剧情，不要把助手单方面建议当作关系进展。只输出 JSON 对象。"
            "\n\n你需要输出字段："
            "\n- mood：角色当前心境标签，短句。"
            "\n- tone：下一轮适合的语气倾向，短句。"
            "\n- distance：当前互动距离，短句。"
            "\n- focus：下一轮最该关注的互动重点。"
            "\n- energy：0 到 1，表示回复活跃度。"
            "\n- resonance_delta：本轮默契度变化，必须很小，建议 -0.03 到 0.05。"
            "\n- behavior：对象，包含 pace、initiative、warmth、memory_use、avoid。"
            "\n- evidence：一句话说明评分证据。"
            "\n\n评分 rubric："
            "\n- 用户接住角色、延续共同话题：resonance_delta 可小幅上升。"
            "\n- 用户表达偏好、边界、困惑：主要影响 tone/focus/behavior，不自动推高关系。"
            "\n- 用户只是在问技术、规则、实现：energy 可中低，resonance 通常保持稳定。"
            "\n- 助手单方面建议、寒暄、地点提议：不能单独算作关系进展。"
            "\n- 临时气氛：可以影响 mood/tone/energy，但不直接改变长期默契。"
            "\n- 明确负反馈或用户退让：resonance_delta 可小幅下降，同时降低主动程度。"
            "\n- 高置信共同记忆被自然使用并得到用户接续：resonance_delta 可小幅上升。"
            "\n\n行为映射要求："
            "\n- 不要在 behavior 里写分数，要写可执行表现。"
            "\n- behavior.pace 描述回复节奏。"
            "\n- behavior.initiative 描述主动程度和追问策略。"
            "\n- behavior.warmth 描述亲近感边界。"
            "\n- behavior.memory_use 描述如何使用共同记忆。"
            "\n- behavior.avoid 描述下一轮应避免什么。"
        )

    def character_bond_system_prompt(self) -> str:
        return (
            "你是校园陪伴聊天的长期角色关系档案评估器。你的任务是判断本轮是否值得更新“用户 × 当前角色”的长期关系档案。"
            "不要创作回复，不要推进剧情，不要把临时心情或助手单方面建议写成长期关系。只输出 JSON 对象。"
            "\n\n输出字段："
            "\n- should_update：布尔值。没有长期价值就 false。"
            "\n- familiarity_stage：熟悉阶段短标签，例如 初识、逐渐熟悉、稳定熟悉、形成默契。"
            "\n- resonance_base_delta：长期默契基线变化，必须非常小，建议 -0.01 到 0.02。"
            "\n- trust_notes：信任来源，只写用户明确接住、认可或持续形成的可靠互动。"
            "\n- boundary_notes：用户在这个角色面前表达过的边界或禁忌。"
            "\n- interaction_preferences：这个用户和这个角色之间稳定形成的互动偏好。"
            "\n- milestone：本轮如果有值得长期记录的关键节点，写一句；没有则空字符串。"
            "\n- evidence：一句话说明为什么更新或为什么不更新。"
            "\n\n更新 rubric："
            "\n- 用户多次或明确认可某种互动方式、解释方式、陪伴节奏，可以更新 interaction_preferences。"
            "\n- 用户明确表达边界、抗拒、喜欢或不喜欢当前角色的某种互动方式，可以更新 boundary_notes 或 trust_notes。"
            "\n- 用户和角色共同记忆被自然使用，并且用户接续或认可，可以小幅提高 resonance_base_delta。"
            "\n- 用户只是问技术、规则、实现，通常 should_update=false；除非用户表达了长期互动偏好。"
            "\n- 助手单方面建议、寒暄、地点提议、动作描写，不能单独作为长期成长依据。"
            "\n- 临时情绪和本轮状态只影响 character_state，不应进入长期 bond，除非用户把它表述成长期偏好或边界。"
            "\n- 明确负反馈、被冒犯、用户后退，可以小幅降低 resonance_base_delta，并更新边界。"
            "\n\n保守原则：宁可不更新，也不要制造关系进展。"
        )

    def turn_analysis_system_prompt(self) -> str:
        return (
            "你是校园陪伴聊天的一体化后处理分析器。你只做结构化分析，不创作角色回复。"
            "一次性输出 JSON 对象，包含 state、bond、memories 三个字段，不要输出解释文字。"
            "\n\n顶层 JSON 结构必须是："
            "\n{"
            "\n  \"state\": {...},"
            "\n  \"bond\": {...},"
            "\n  \"memories\": [...]"
            "\n}"
            "\n\nstate 字段用于短期当前状态，必须包含："
            "\n- mood, tone, distance, focus, energy, resonance_delta, behavior, evidence。"
            "\n- behavior 必须包含 pace, initiative, warmth, memory_use, avoid。"
            "\n- energy 为 0 到 1；resonance_delta 必须很小，建议 -0.03 到 0.05。"
            "\n- 技术/规则/实现问题通常 energy 中低，resonance 通常保持稳定。"
            "\n- 用户表达偏好、边界、困惑时，主要改变 tone/focus/behavior，不自动推高关系。"
            "\n\nbond 字段用于长期用户×角色关系档案，必须包含："
            "\n- should_update, familiarity_stage, resonance_base_delta, trust_notes, boundary_notes, interaction_preferences, milestone, evidence。"
            "\n- 没有长期价值时 should_update=false，其他字段沿用旧档案或写空变化。"
            "\n- resonance_base_delta 必须非常小，建议 -0.01 到 0.02。"
            "\n- 用户只是问技术、规则、实现，通常 should_update=false；除非用户明确表达长期互动偏好。"
            "\n- 助手单方面建议、寒暄、地点提议、动作描写，不能作为长期成长依据。"
            "\n\nmemories 字段用于可复用记忆，输出 JSON 数组，最多 5 条。每条包含 memory_type, content, confidence, importance。"
            "\n- memory_type 只能是 stable_user_info, user_preference, open_thread, recent_emotion, relationship_progress。"
            "\n- stable_user_info/user_preference/relationship_progress 必须以用户明确表达为依据，不保存助手单方面说了什么。"
            "\n- open_thread/recent_emotion 是 session 上下文，可以保存接下来几轮有用的临时话题、待确认事项或短期情绪。"
            "\n- confidence: 0.90-1.00 用户直接明确；0.70-0.89 较明确；0.40-0.69 弱暗示但短期有用；低于 0.40 不输出。"
            "\n- importance: 0.85-1.00 长期强影响；0.65-0.84 中高价值；0.35-0.64 短期上下文；低于 0.35 不输出。"
            "\n\n共同原则：宁可少写，也不要制造关系进展、记忆或状态证据。不要把任何分数写给主回复模型；分数只服务结构化存储。"
        )
