from __future__ import annotations


class LlmPromptMixin:
    def memory_extraction_system_prompt(self) -> str:
        return (
            "你是保守但不健忘的聊天记忆抽取器。抽取关于“用户”的、未来可复用的事实、偏好、状态、承诺、关系进展，"
            "也可以保留对接下来几轮有帮助的短期上下文。"
            "长期记忆要严格，短期 session 上下文要宽松。"
            "stable_user_info、user_preference、relationship_progress 不要保存助手单方面说了什么、问了什么、建议了什么。"
            "open_thread、recent_emotion 属于 session 上下文，可以保存对接下来几轮有用的对话状态、临时话题、地点建议、待确认事项或用户正在回应的助手建议。"
            "如果用户没有明确表达可复用信息，输出 []。只输出 JSON 数组，不要解释。"
            "\n\nmemory_type 只能是："
            "\n- stable_user_info：稳定身份、长期背景、长期习惯，例如专业、常住地、长期作息。"
            "\n- user_preference：用户明确喜欢/不喜欢/偏好的互动方式或事物。"
            "\n- open_thread：session 级上下文。可以记录之后要继续、要做、要回来看、还没完成的话题，也可以记录接下来几轮需要承接的临时上下文。"
            "\n- recent_emotion：session 级上下文。记录用户当前或最近的情绪状态，也可记录会影响接下来几轮语气的短期状态。"
            "\n- relationship_progress：用户和当前角色之间明确发生的关系变化、信任、边界或承诺。"
            "\n\nconfidence 评分："
            "\n- 0.97-1.00：用户以事实句直接确认稳定信息，且几乎没有语境歧义，例如“我叫许砚清”“我住在杭州”。这档要少用。"
            "\n- 0.90-0.96：用户明确表达长期偏好、边界、身份或承诺，但仍可能需要一点语境解释，例如“我不喜欢被一直追问”。"
            "\n- 0.80-0.89：用户表达清楚，但对象、范围或持续性不是完全确定，例如“我最近喜欢安静一点”。"
            "\n- 0.65-0.79：用户倾向明显，但需要结合上下文理解，例如“这样也挺好”“我一般不太带东西去湖边”。"
            "\n- 0.40-0.64：只是弱暗示或推断，只适合 open_thread/recent_emotion 等短期上下文。"
            "\n- 0.00-0.39：不可靠，不要输出。"
            "\n- 不要把所有明确表达都打成 0.90 或 0.95；只有身份事实、强偏好、强边界才进入 0.90 以上。"
            "\n\nimportance 评分："
            "\n- 0.85-1.00：长期强影响，未来多次对话都应优先参考，例如强偏好、重要边界、长期身份。"
            "\n- 0.65-0.84：中高价值，相关话题应召回，例如兴趣偏好、仍要继续的计划。"
            "\n- 0.35-0.64：session 短期上下文有用，只影响接下来几轮，例如今天的情绪、临时安排、地点建议、刚形成的待续话题。"
            "\n- 0.00-0.34：完全无承接价值的一次性闲聊或普通寒暄，不要输出。"
            "\n\n输出要求："
            "\n- 每项包含 memory_type, content, confidence, importance。"
            "\n- 对 global/character 价值的内容，content 必须以用户为主体。"
            "\n- 对 session 上下文，content 可以写成“当前会话正在讨论/待确认/刚提到...”，允许保留必要上下文。"
            "\n- session 短期上下文的 confidence 通常在 0.55-0.85；除非用户直接确认，不要给 0.90 以上。"
            "\n- 可保存的记忆 importance 通常不要低于 0.35；低于 0.35 的内容直接不输出。"
            "\n- 最多输出 5 条。宁可少记，也不要把普通流水账当长期记忆。"
        )

    def character_state_system_prompt(self) -> str:
        return (
            "你是当前角色关系语境下的轻量角色状态评分器。你只根据给定对话和证据判断当前互动状态，"
            "不要创作回复，不要推进剧情，不要把助手单方面建议当作关系进展。只输出 JSON 对象。"
            "\n\n你需要输出字段："
            "\n- mood：角色当前心境标签，短句。"
            "\n- tone：下一轮适合的语气倾向，短句。"
            "\n- distance：当前互动距离，短句。"
            "\n- focus：下一轮最该关注的互动重点。"
            "\n- energy：0 到 1，表示回复活跃度。"
            "\n- resonance_delta：本轮默契度变化，必须很小，建议 -0.03 到 0.05。"
            "\n- behavior：对象，包含 pace、initiative、warmth、memory_use、avoid。"
            "\n- evidence：一句话说明评分证据。"
            "\n\n评分 rubric："
            "\n- 用户接住角色、延续共同话题：resonance_delta 可小幅上升。"
            "\n- 用户表达偏好、边界、困惑：主要影响 tone/focus/behavior，不自动推高关系。"
            "\n- 用户只是在问技术、规则、实现：energy 可中低，resonance 通常保持稳定。"
            "\n- 助手单方面建议、寒暄、地点提议：不能单独算作关系进展。"
            "\n- 临时气氛：可以影响 mood/tone/energy，但不直接改变长期默契。"
            "\n- 明确负反馈或用户退让：resonance_delta 可小幅下降，同时降低主动程度。"
            "\n- 高置信共同记忆被自然使用并得到用户接续：resonance_delta 可小幅上升。"
            "\n\n行为映射要求："
            "\n- 不要在 behavior 里写分数，要写可执行表现。"
            "\n- behavior.pace 描述回复节奏。"
            "\n- behavior.initiative 描述主动程度和追问策略。"
            "\n- behavior.warmth 描述亲近感边界。"
            "\n- behavior.memory_use 描述如何使用共同记忆。"
            "\n- behavior.avoid 描述下一轮应避免什么。"
        )

    def relationship_event_system_prompt(self) -> str:
        grounding_rules = (
            "\n\nAdditional grounding rules:"
            "\n- Positive events used for scoring must be grounded in the user's words; an assistant-only reply, action, or follow-up question is not enough."
            "\n- Ordinary acknowledgements, topic switches, scheduling, short continuations, and casual chat usually output [] unless the user explicitly confirms a relationship fact."
            "\n- boundary_respected needs an explicit boundary or the user's explicit acknowledgement of a respected adjustment; changing to an ordinary topic alone is not enough."
            "\n- shared_context needs a concrete shared fact, pact, or recalled event named by the user; a generic continuation is not enough."
        )
        return (
            "你是当前角色关系语境下的关系事件抽取器。你只判断本轮是否出现可落地的“用户 × 当前角色”关系事件。"
            "不要创作回复，不要推进剧情，不要输出关系阶段，不要输出任何评分、分数变化或自由数值 confidence。"
            "只输出 JSON 数组；没有可用事件时输出 []。"
            "\n\n每条事件只能包含：event_type, evidence_grade, evidence_text。"
            "\n- event_type 只能是 shared_context, preference_confirmed, trust_signal, emotional_disclosure, "
            "boundary_respected, negative_feedback, boundary_violation, repair。"
            "\n- evidence_text 必须直接摘录或紧贴给定聊天上下文，不能写成你自己的总结推断。"
            "\n- 不要输出 score、delta、stage、familiarity_stage、resonance、confidence。"
            "\n\n证据等级："
            "\n- explicit：用户明确说出、确认或拒绝了关系相关事实、偏好、边界、约定。"
            "\n- strong：本轮有直接文本证据，只有很少推断。"
            "\n- contextual：依赖上下文推断，证据不够直接。"
            "\n- weak：主要靠气氛猜测、含糊联想或角色单方面动作。"
            "\n\n抽取 rubric："
            "\n- shared_context：用户接续共同经历、共同约定或双方都明确承接的上下文。"
            "\n  只说“刚才那样”“这个也挺好”但没有指明共同经历或约定，不算 explicit shared_context；最多给 contextual。"
            "\n- preference_confirmed：用户明确确认与当前角色互动时的稳定偏好。"
            "\n- trust_signal：必须由用户明确表现信任、托付、认可角色可靠性；助手承诺或安慰自己不能算 trust_signal。"
            "\n- emotional_disclosure：用户主动向当前角色披露有关系意义的情绪或脆弱信息。"
            "\n- boundary_respected：边界被明确提出并被当前互动尊重。"
            "\n- negative_feedback：用户明确表达失望、后退、拒绝当前互动方式。"
            "\n- boundary_violation：出现明确冒犯、越界或用户指出边界被踩。"
            "\n- repair：负向互动后用户明确接受修复、接受调整或重新达成边界共识。"
            "\n  例如用户说“你停下来重新问我，我能接受”时优先抽 repair，不要抽成 shared_context 或 trust_signal。"
            "\n\n去重与优先级："
            "\n- 同一段证据只抽最关键的一种事件。"
            "\n- 明确越界时优先 boundary_violation，不要再用同一句话重复抽 negative_feedback。"
            "\n- 明确修复时优先 repair，不要把同一句话重复抽成 shared_context 或 trust_signal。"
            "\n\n保守原则：用户只是问技术、规则、实现或普通寒暄时通常输出 []；宁可少抽取，也不要制造关系进展。"
        ) + grounding_rules

    def character_bond_system_prompt(self) -> str:
        return self.relationship_event_system_prompt()

    def turn_analysis_system_prompt(self) -> str:
        return (
            "你是当前角色关系语境下的一体化后处理分析器。你只做结构化分析，不创作角色回复。"
            "一次性输出 JSON 对象，包含 state、bond、memories 三个字段，不要输出解释文字。"
            "\n\n顶层 JSON 结构必须是："
            "\n{"
            "\n  \"state\": {...},"
            "\n  \"bond\": [...],"
            "\n  \"memories\": [...]"
            "\n}"
            "\n\nstate 字段用于短期当前状态，必须包含："
            "\n- mood, tone, distance, focus, energy, resonance_delta, behavior, evidence。"
            "\n- behavior 必须包含 pace, initiative, warmth, memory_use, avoid。"
            "\n- energy 为 0 到 1；resonance_delta 必须很小，建议 -0.03 到 0.05。"
            "\n- 技术/规则/实现问题通常 energy 中低，resonance 通常保持稳定。"
            "\n- 用户表达偏好、边界、困惑时，主要改变 tone/focus/behavior，不自动推高关系。"
            "\n\nbond 字段用于长期关系事件抽取，必须输出 JSON 数组。"
            "\n- 数组项只包含 event_type, evidence_grade, evidence_text。"
            "\n- 不要输出关系阶段、分数、delta 或自由数值 confidence。"
            "\n- 用户只是问技术、规则、实现，通常输出 []。"
            "\n- 助手单方面建议、寒暄、地点提议、动作描写，不能作为长期关系事件。"
            "\n\nmemories 字段用于可复用记忆，输出 JSON 数组，最多 5 条。每条包含 memory_type, content, confidence, importance。"
            "\n- memory_type 只能是 stable_user_info, user_preference, open_thread, recent_emotion, relationship_progress。"
            "\n- stable_user_info/user_preference/relationship_progress 必须以用户明确表达为依据，不保存助手单方面说了什么。"
            "\n- open_thread/recent_emotion 是 session 上下文，可以保存接下来几轮有用的临时话题、待确认事项或短期情绪。"
            "\n- confidence: 0.97-1.00 稳定事实且无歧义；0.90-0.96 明确长期偏好/边界/身份；0.80-0.89 清楚但范围或持续性不完全确定；0.65-0.79 倾向明显但依赖上下文；0.40-0.64 弱暗示且只适合短期上下文；低于 0.40 不输出。不要把所有明确表达都打成 0.90 或 0.95。"
            "\n- importance: 0.85-1.00 长期强影响；0.65-0.84 中高价值；0.35-0.64 短期上下文；低于 0.35 不输出。"
            "\n\n共同原则：宁可少写，也不要制造关系进展、记忆或状态证据。不要把任何分数写给主回复模型；分数只服务结构化存储。"
        )
